name: 'Pull Request Reminder Bot'
description: 'Send slack or discord messages to remind reviewing pull requests.'
inputs:
  MESSENGER_TYPE:
    description: 'messenger type Slack or Discord default Slack'
    required: false
    default: 'slack'
  OWNER:
    description: 'owner of github repositories'
    required: true
  REPOS:
    description: 'target repositories. ex : "abc,def,zxc"'
    required: true
  WEBHOOK_URL:
    description: 'Slack or Discord Webhook URL'
    required: true
  MESSENGER_GITHUB_MAP:
    description: 'Map GitHub username to messenger member ID. ex: "spotlight21c:UBCDEFGHI,DavideViolante:UABCDEFGH"'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
