name: pull-request-reminder-action
on:
  push:
    branches:
      - 'main'

jobs:
  pull_request_reminder_action:
    runs-on: ubuntu-latest
    steps:
      - uses: rrgks6221/pr-notification-bot/@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          MESSENGER_TYPE: ${{ secrets.MESSENGER_TYPE }}
          OWNER: ${{ secrets.OWNER }}
          REPOS: ${{ secrets.REPOS }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          MESSENGER_GITHUB_MAP: ${{ secrets.MESSENGER_GITHUB_MAP }}
